checks:
  php: true

filter:
  excluded_paths:
    - 'features/'
    - 'tests/'

build:
  environment:
    # Languages
    php:
      version: "7.4"
      ini:
        memory_limit:     "-1"

  tests:
    override:
      -
        command: 'vendor/bin/phpunit --exclude-group efficiency'
        idle_timeout: 3600
        coverage:
            file: 'build/coverage-phpunit/clover.xml'
            format: 'clover'
      -
        command: 'vendor/bin/behat'
        coverage:
            file: 'build/coverage-behat/clover.xml'
            format: 'clover'
      - php-scrutinizer-run
