group: travis_latest
language: php

matrix:
  include:
    - php: 5.4
      env: lowest=1
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  - phpenv config-rm xdebug.ini || true;

  - |
    if [ "$lowest" = "1" ]; then
      composer update --prefer-lowest --prefer-stable;
    else
      composer update;
    fi;

before_script:
  - |
    if [ "$TRAVIS_PHP_VERSION" != "5.4" ] && [ "$TRAVIS_PHP_VERSION" != "5.5" ] && [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then
      echo "memory_limit = 3072M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    fi;

script:
  - php vendor/bin/phpunit;
  - php vendor/bin/behat --strict;
